name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'
  release:
    types:
      - published

jobs:
  test:
    name: libRDChEBI (${{ matrix.os }}, ${{ matrix.python-version }}, ${{ matrix.chembl-structure-pipeline-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        chembl-structure-pipeline-version: ["1.2.0"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest build chembl_structure_pipeline==${{ matrix.chembl-structure-pipeline-version }}
      - name: Test with pytest
        run: |
          pytest --doctest-modules

      - name: Build wheels
        run: python -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: dist/*

  upload_all:
    name: Upload if release
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.5.1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}